version: "3.8"

name: "movix_tests"

volumes:
  redis_data_local: {}

services:
  api:
    image: ghcr.io/stranded-in-python/movix-api:dev
    stdin_open: true
    volumes:
      - ./src:/app:z
    depends_on:
      - redis
      - elastic
    command: sh -c "pytest /app"
    ports:
      - "8001:8000"
    environment:
      REDIS_HOST: "redis"
      ELASTIC_ENDPOINT: "http://elastic:9200"

  redis:
    image: redis:7.2-rc-bullseye
    volumes:
      - redis_data_local:/data
    ports:
      - "6379:6379"

  elastic:
    image: ghcr.io/stranded-in-python/movix-elastic:ftests
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
