version: "3.8"

name: "movix_tests"

volumes:
  redis_data_local: {}

services:
  api:
    image: ghcr.io/stranded-in-python/movix-api:dev
    stdin_open: true
    volumes:
      - ./src:/app:z
    command: sh -c "pytest /app/tests/test_services/ --asyncio-mode=auto -W ignore::DeprecationWarning
      && pytest /app/tests/functional/ --asyncio-mode=auto -W ignore::DeprecationWarning
      && pytest /app/tests/test_db --asyncio-mode=auto -W ignore::DeprecationWarning"
    ports:
      - "8001:8000"
    depends_on:
      - redis
      - elastic
    environment:
      redis_host: redis
      elastic_endpoint: http://elastic:9200

  redis:
    image: redis:7.2-rc-bullseye
    volumes:
      - redis_data_local:/data
    ports:
      - "6379:6379"

  elastic:
    image: ghcr.io/stranded-in-python/movix-elastic:ftests
    #volumes:
    #  - elastic_data_local:/usr/share/elasticsearch/data
    #env_file:
    #  - ./.envs/.local/.elastic
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
