version: "3.8"

name: "movix_tests"

services:
  api:
    image: ghcr.io/stranded-in-python/movix-api:dev
    stdin_open: true
    volumes:
      - ./src:/app:z
    entrypoint: "pytest /app/tests/test_services/ && pytest /app/tests/functional/ && pytest /app/tests/test_db"
    ports:
      - "8001:8000"
