#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset



elastic_ready() {
python << END
import sys
import httpx
import pprint

elastic_server = '${ELASTIC_ENDPOINT}'
url = f'{elastic_server}/_cluster/health'
try:
    print(f'Checking status of elastic at {url}...')
    response = httpx.get(url)
    if response.status_code == 200:
        sys.exit(0)
    else:
        sys.exit(-1)
except httpx.RequestError as e:
  pprint.pp(e)
  sys.exit(-1)
END
}

backoff() {
  local timeout=1;
  until elastic_ready; do
    >&2 echo 'Waiting for ElasticSearch to become available...'
    sleep $timeout
    timeout=$(( timeout * 2 ));
  done
  >&2 echo 'ElasticSearch is available'
}

backoff

exec "$@"
