#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset



elastic_ready() {
python << END
import sys
import requests

elastic_server = '${ELASTIC_ENDPOINT}'
url = f'{elastic_server}/_cluster/health'
try:
    response = requests.get(url)
    if response.ok:
        sys.exit(0)
    else:
        sys.exit(-1)
except requests.exceptions.RequestException as e:
  sys.exit(-1)
END
}

until elastic_ready; do
  >&2 echo 'Waiting for ElasticSearch to become available...'
  sleep 1
done
>&2 echo 'ElasticSearch is available'

exec "$@"
